"""
Stack — the deployment contract for infracloud.

A Stack describes WHAT runs on a GPU server. InfraCloud uses it to know
which Docker image to use, how much GPU/disk to request, what script to run
on startup, and how to verify the server is ready to accept requests.

Stacks can be:
  - Directory-based: a directory under ``stacks/`` with a ``pyproject.toml``
    containing ``[tool.infracloud]`` metadata (preferred, reproducible)
  - Custom YAML: any project can define its own stack in a .yaml file
  - Programmatic: constructed inline as a Python object

Example (directory-based, loaded automatically by the stacks registry):

    # stacks/my-stack/pyproject.toml
    # [tool.infracloud]
    # image = "vastai/pytorch"
    # gpu_vram_gb = 24
    # ports = [5000]
    # entrypoint = "serve.py"

    # Then just run:
    #   infracloud up my-stack

Example (programmatic):

    from infracloud.stack import Stack

    my_stack = Stack(
        name="my-server",
        image="vastai/base-image:cuda-12.4.1-cudnn-devel-ubuntu22.04",
        gpu_vram_gb=24,
        disk_gb=50,
        ports=[5000],
        onstart=\"\"\"
            #!/bin/bash
            source /venv/main/bin/activate
            pip install fastapi uvicorn
            python /workspace/serve.py &
        \"\"\",
        health_url="/health",
    )

Example (from YAML file):

    stack = Stack.from_yaml("./my-stack.yaml")

    # my-stack.yaml:
    # name: my-server
    # image: vastai/base-image:cuda-12.4.1-cudnn-devel-ubuntu22.04
    # gpu_vram_gb: 24
    # disk_gb: 50
    # ports: [5000]
    # onstart: |
    #   #!/bin/bash
    #   pip install fastapi uvicorn
    #   python /workspace/serve.py &
    # health_url: /health
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Stack:
    """Describes a deployable workload for a GPU server on Vast.ai.

    Attributes:
        name:          Human-readable identifier (e.g. "ltx-video", "comfyui").
        image:         Docker image to use. Prefer vastai/base-image variants as
                       they are pre-cached on Vast.ai hosts for faster startup.
        gpu_vram_gb:   Minimum GPU VRAM in GB required by the workload.
        disk_gb:       Disk space to allocate in GB (model weights + deps).
        ports:         List of ports the server listens on inside the container.
                       Vast.ai will map these to random external ports.
        onstart:       Bash script that runs automatically when the instance
                       boots. Used directly for ``onstart_mode="custom"`` stacks,
                       or left empty for ``onstart_mode="uv"`` stacks (the script
                       is generated by :meth:`build_onstart`).
        health_url:    HTTP path to poll to determine if the server is ready.
                       infracloud will GET http://host:port{health_url} until it
                       receives a 200 response (or times out).
        health_port:   Which port from ``ports`` to use for the health check.
                       Defaults to the first port in ``ports`` if not set.
        env:           Extra environment variables to set on the instance.
                       Values may contain ``${VAR}`` references which are
                       resolved from the local environment at runtime.
        min_cuda_ver:  Minimum CUDA version required by the workload
                       (e.g. ``12.9``). When set, only Vast.ai hosts whose
                       driver supports at least this CUDA version will be
                       considered. Leave as ``None`` to accept any host.
        template_hash: Vast.ai template hash ID for official images that use
                       ``@vastai-automatic-tag`` (e.g. ``vastai/pytorch``,
                       ``vastai/comfy``).  When set, infracloud passes it to
                       ``create_instance`` and omits the explicit ``image``
                       argument so Vast.ai can auto-select the right CUDA
                       tag for the target host.  Leave as ``None`` for
                       plain Docker images where a full tag is specified.
        stack_dir:     Path of the stack directory relative to the repo root
                       (e.g. ``"stacks/ltx-video"``). Set automatically by
                       :meth:`from_dir`. Used by :meth:`build_onstart` to know
                       where to ``cd`` after cloning the repo.
        entrypoint:    Python file to execute inside ``stack_dir`` after
                       ``uv sync`` completes (e.g. ``"serve.py"``). Only used
                       when ``onstart_mode="uv"``.
        onstart_mode:  How to generate the onstart script:
                       - ``"uv"`` (default): auto-generate a standardised script
                         that clones the repo, runs ``uv sync --frozen``, and
                         executes ``entrypoint``.
                       - ``"custom"``: use the ``onstart`` field as-is (legacy /
                         special stacks like ComfyUI).
        repo_url:      URL of the git repository to clone on the remote instance
                       (e.g. ``"https://github.com/user/infracloud.git"``).
                       Required for ``onstart_mode="uv"``. Can be set here, in
                       ``[tool.infracloud]``, or injected at runtime via the
                       ``INFRACLOUD_REPO_URL`` environment variable.
    """

    name: str
    image: str
    gpu_vram_gb: int = 24
    disk_gb: int = 50
    ports: list[int] = field(default_factory=lambda: [5000])
    onstart: str = ""
    health_url: str = "/health"
    health_port: int | None = None
    env: dict[str, str] = field(default_factory=dict)
    min_cuda_ver: float | None = None
    template_hash: str | None = None
    # ── Directory-based stack fields ──────────────────────────────────────────
    stack_dir: str | None = None
    entrypoint: str | None = None
    onstart_mode: str = "uv"
    repo_url: str | None = None

    def __post_init__(self) -> None:
        if not self.name:
            raise ValueError("Stack.name cannot be empty")
        if not self.image:
            raise ValueError("Stack.image cannot be empty")
        if not self.ports:
            raise ValueError("Stack.ports must contain at least one port")
        if self.gpu_vram_gb < 1:
            raise ValueError("Stack.gpu_vram_gb must be >= 1")
        if self.disk_gb < 1:
            raise ValueError("Stack.disk_gb must be >= 1")

    @property
    def effective_health_port(self) -> int:
        """The port used for health checks (defaults to first port in ports)."""
        return self.health_port if self.health_port is not None else self.ports[0]

    # ── Loaders ───────────────────────────────────────────────────────────────

    @classmethod
    def get(cls, name: str) -> Stack | None:
        """Look up a built-in stack by name (= directory name under ``stacks/``).

        Scans the ``stacks/`` directory at the repository root (three levels up
        from this file: ``infracloud/stack.py`` → ``../../..`` → repo root).

        Args:
            name: The stack name, e.g. ``"ltx-video"`` or ``"comfyui"``.

        Returns:
            A :class:`Stack` loaded from ``stacks/{name}/pyproject.toml``,
            or ``None`` if the directory or ``pyproject.toml`` does not exist.
        """
        stacks_root = Path(__file__).resolve().parent.parent / "stacks"
        stack_dir = stacks_root / name
        if not stack_dir.is_dir():
            return None
        if not (stack_dir / "pyproject.toml").exists():
            return None
        return cls.from_dir(stack_dir)

    @classmethod
    def list_available(cls) -> list[str]:
        """Return the names of all available built-in stacks.

        Scans the ``stacks/`` directory at the repository root for
        subdirectories that contain a ``pyproject.toml``.

        Returns:
            Sorted list of stack names (directory names), e.g.
            ``["comfyui", "ltx-video"]``.
        """
        stacks_root = Path(__file__).resolve().parent.parent / "stacks"
        if not stacks_root.is_dir():
            return []
        return sorted(
            d.name
            for d in stacks_root.iterdir()
            if d.is_dir() and (d / "pyproject.toml").exists()
        )

    @classmethod
    def from_dir(cls, path: str | Path) -> Stack:
        """Load a Stack from a directory containing a ``pyproject.toml`` with
        ``[tool.infracloud]`` metadata.

        This is the preferred way to define a stack. The directory should contain:

        - ``pyproject.toml`` with a ``[tool.infracloud]`` section
        - ``serve.py`` (or whatever ``entrypoint`` is set to) for uv stacks
        - ``onstart.sh`` for stacks with ``onstart_mode = "custom"``

        The stack name is taken from the directory name (e.g. ``stacks/ltx-video``
        → ``name="ltx-video"``).

        ``stack_dir`` is set to the path relative to the repository root. The repo
        root is detected by walking up from ``path`` until a directory containing
        ``pyproject.toml`` (without ``[tool.infracloud]``) or ``.git`` is found.
        Falls back to the path itself if detection fails.

        Environment variable values in ``[tool.infracloud.env]`` may contain
        ``${VAR}`` references, which are resolved from the local environment
        at load time (e.g. ``HF_TOKEN = "${HF_TOKEN}"``).

        Args:
            path: Path to the stack directory (absolute or relative to cwd).

        Returns:
            A :class:`Stack` instance populated from ``pyproject.toml``.

        Raises:
            FileNotFoundError: If ``pyproject.toml`` does not exist in ``path``.
            ValueError: If ``[tool.infracloud]`` section is missing or invalid.
        """
        import tomllib  # stdlib since Python 3.11

        stack_path = Path(path).resolve()
        pyproject_path = stack_path / "pyproject.toml"

        if not pyproject_path.exists():
            raise FileNotFoundError(
                f"No pyproject.toml found in {stack_path}"
            )

        with open(pyproject_path, "rb") as f:
            data = tomllib.load(f)

        tool = data.get("tool", {})
        ic = tool.get("infracloud")
        if ic is None:
            raise ValueError(
                f"No [tool.infracloud] section found in {pyproject_path}"
            )

        # Detect repo root to compute stack_dir as a relative path
        repo_root = _find_repo_root(stack_path)
        try:
            stack_dir_rel = str(stack_path.relative_to(repo_root))
        except ValueError:
            stack_dir_rel = str(stack_path)

        # Resolve env vars — support ${VAR} substitution for secrets
        raw_env: dict = ic.pop("env", {})
        resolved_env: dict[str, str] = {
            k: _resolve_env_value(str(v)) for k, v in raw_env.items()
        }

        # Extract known fields; unknown keys are silently ignored
        known_fields = {
            "image", "template_hash", "gpu_vram_gb", "disk_gb", "ports",
            "health_url", "health_port", "min_cuda_ver", "entrypoint",
            "onstart_mode", "repo_url",
        }
        kwargs: dict = {k: v for k, v in ic.items() if k in known_fields}

        onstart_mode = kwargs.get("onstart_mode", "uv")

        # For custom stacks, load onstart.sh from the directory
        onstart = ""
        if onstart_mode == "custom":
            onstart_sh = stack_path / "onstart.sh"
            if onstart_sh.exists():
                onstart = onstart_sh.read_text(encoding="utf-8")

        return cls(
            name=stack_path.name,
            stack_dir=stack_dir_rel,
            env=resolved_env,
            onstart=onstart,
            **kwargs,
        )

    @classmethod
    def from_yaml(cls, path: str) -> Stack:
        """Load a Stack from a YAML file.

        This allows any external project to define a stack without writing
        Python — just a simple YAML file with the same field names.

        Args:
            path: Path to the YAML file (absolute or relative to cwd).

        Returns:
            A Stack instance populated from the YAML data.

        Raises:
            FileNotFoundError: If the YAML file does not exist.
            ValueError: If required fields are missing or invalid.
        """
        import yaml  # optional import — only needed when using YAML stacks

        with open(path) as f:
            data = yaml.safe_load(f)

        if not isinstance(data, dict):
            raise ValueError(f"Expected a YAML mapping at the top level in {path!r}")

        # Allow 'ports' to be a single int in YAML for convenience
        if "ports" in data and isinstance(data["ports"], int):
            data["ports"] = [data["ports"]]

        # Allow 'env' to be absent in YAML
        data.setdefault("env", {})

        return cls(**data)

    # ── Onstart generation ────────────────────────────────────────────────────

    def build_onstart(self) -> str:
        """Generate (or return) the bash onstart script for this stack.

        For ``onstart_mode="custom"`` stacks, this returns the ``onstart``
        field verbatim (the script was loaded from ``onstart.sh`` by
        :meth:`from_dir`, or set manually).

        For ``onstart_mode="uv"`` stacks (the default), this generates a
        standardised script that:

        1. Installs ``uv`` (the fast Python package manager)
        2. Clones the infracloud repo (``repo_url``) to ``/workspace/infracloud``
        3. Activates the pre-existing venv at ``/venv/main``
        4. Sets ``UV_PROJECT_ENVIRONMENT=/venv/main`` so ``uv sync`` installs
           into the existing torch/CUDA venv rather than creating a new one
        5. Runs ``uv sync --frozen --no-install-project`` inside the stack
           directory to install pinned deps from ``uv.lock``
        6. Executes ``entrypoint`` with Python

        Returns:
            The bash script as a string. Returns an empty string if the stack
            has no onstart and no entrypoint configured.

        Raises:
            ValueError: If ``onstart_mode="uv"`` but ``repo_url`` or
                        ``entrypoint`` is not set.
        """
        if self.onstart_mode == "custom":
            return self.onstart

        # uv mode — generate standardised script
        if not self.repo_url:
            raise ValueError(
                f"Stack {self.name!r}: repo_url is required for onstart_mode='uv'. "
                "Set it in [tool.infracloud] or via INFRACLOUD_REPO_URL env var."
            )
        if not self.entrypoint:
            raise ValueError(
                f"Stack {self.name!r}: entrypoint is required for onstart_mode='uv'. "
                "Set it in [tool.infracloud] (e.g. entrypoint = \"serve.py\")."
            )
        if not self.stack_dir:
            raise ValueError(
                f"Stack {self.name!r}: stack_dir is required for onstart_mode='uv'. "
                "Use Stack.from_dir() to load the stack from its directory."
            )

        return f"""#!/bin/bash
set -e

echo "[infracloud] Installing uv..."
curl -LsSf https://astral.sh/uv/install.sh | sh
export PATH="$HOME/.local/bin:$PATH"

echo "[infracloud] Cloning repository..."
git clone --depth 1 {self.repo_url} /workspace/infracloud

echo "[infracloud] Installing dependencies..."
cd /workspace/infracloud/{self.stack_dir}
source /venv/main/bin/activate
export UV_PROJECT_ENVIRONMENT=/venv/main
uv sync --frozen --no-install-project

echo "[infracloud] Starting server..."
python /workspace/infracloud/{self.stack_dir}/{self.entrypoint}
"""

    # ── Repr ──────────────────────────────────────────────────────────────────

    def __repr__(self) -> str:
        return (
            f"Stack(name={self.name!r}, image={self.image!r}, "
            f"gpu_vram_gb={self.gpu_vram_gb}, ports={self.ports})"
        )


# ── Helpers ───────────────────────────────────────────────────────────────────

def _find_repo_root(start: Path) -> Path:
    """Walk up from *start* to find the repository root.

    The root is identified by the presence of a ``.git`` directory or a
    ``pyproject.toml`` that does NOT contain ``[tool.infracloud]`` (i.e. it is
    the project root, not a stack sub-project).

    Falls back to *start* if no root is detected.
    """
    import tomllib

    current = start
    while True:
        # .git directory is the most reliable root marker
        if (current / ".git").exists():
            return current
        # pyproject.toml without [tool.infracloud] = project root
        pyproject = current / "pyproject.toml"
        if pyproject.exists() and pyproject != (start / "pyproject.toml"):
            try:
                with open(pyproject, "rb") as f:
                    data = tomllib.load(f)
                if "infracloud" not in data.get("tool", {}):
                    return current
            except Exception:
                pass
        parent = current.parent
        if parent == current:
            # Reached filesystem root without finding a repo root
            return start
        current = parent


_ENV_VAR_RE = re.compile(r"\$\{([^}]+)\}")


def _resolve_env_value(value: str) -> str:
    """Replace ``${VAR}`` references in *value* with values from ``os.environ``.

    Unknown variables are left as-is (not expanded).

    Example::

        os.environ["HF_TOKEN"] = "hf_abc123"
        _resolve_env_value("${HF_TOKEN}")   # → "hf_abc123"
        _resolve_env_value("static_value")  # → "static_value"
    """
    def _replace(match: re.Match) -> str:
        var_name = match.group(1)
        return os.environ.get(var_name, match.group(0))  # keep original if missing

    return _ENV_VAR_RE.sub(_replace, value)
